export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CART_REQUEST = "CART_REQUEST"
export const CART_ADD_FAIL = "CART_ADD_FAIL"
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL"

export const CART_ADD_SHIPPING_ADDRESS = "CART_ADD_SHIPPING_ADDRESS"
export const CART_ADD_PAYMENT_METHOD = "CART_ADD_PAYMENT_METHOD"
